-- MySQL Script generated by MySQL Workbench
-- Thu 20 Sep 2018 08:08:15 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema parking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parking` DEFAULT CHARACTER SET latin1 ;
USE `parking` ;

-- -----------------------------------------------------
-- Table `parking`.`reserve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`reserve` (
  `id_plot` INT(11) NOT NULL,
  `id_parking` INT(11) NOT NULL,
  `init_time` TIME NULL DEFAULT NULL,
  `time_reserve` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_parking`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `parking`.`user_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`user_app` (
  `nome` VARCHAR(20) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `reserve_id_parking` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `reserve_id_parking`),
  INDEX `fk_user_app_reserve_idx` (`reserve_id_parking` ASC),
  CONSTRAINT `fk_user_app_reserve`
    FOREIGN KEY (`reserve_id_parking`)
    REFERENCES `parking`.`reserve` (`id_parking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `parking`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`car` (
  `car_plate` VARCHAR(7) NOT NULL,
  `color` VARCHAR(10) NOT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  `user_app_id` INT(11) NOT NULL,
  `user_app_reserve_id_parking` INT(11) NOT NULL,
  PRIMARY KEY (`car_plate`, `user_app_id`, `user_app_reserve_id_parking`),
  INDEX `fk_car_user_app1_idx` (`user_app_id` ASC, `user_app_reserve_id_parking` ASC),
  CONSTRAINT `fk_car_user_app1`
    FOREIGN KEY (`user_app_id` , `user_app_reserve_id_parking`)
    REFERENCES `parking`.`user_app` (`id` , `reserve_id_parking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
